/**
 * <copyright>
 * Copyright (c) 2026, AGG XML Serialization Refactoring Project.
 * All rights reserved.
 * </copyright>
 */
package agg.xml.validation;

import agg.xt_basis.GraGra;
import agg.xt_basis.Graph;
import agg.xt_basis.Rule;
import agg.xml.TestDataHelper;
import agg.xml.XMLSerialization;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import static org.testng.Assert.*;

import java.io.File;
import java.util.List;
import java.util.Map;

/**
 * Regression tests using preserved legacy XML fixtures.
 *
 * <p>Legacy XML files were generated by the old XMLHelper / XwriteObject path
 * and are preserved in {@code assets_test_xml/test_agg/legacy/}. These tests
 * verify that the new DOM-based serialization can:
 * <ol>
 *   <li>Load each legacy XML file correctly (DOM deserialization).</li>
 *   <li>Save the loaded structure to a new XML file (DOM serialization).</li>
 *   <li>Reload the saved file and verify structural equivalence
 *       (DOM path stability).</li>
 * </ol>
 *
 * <p>This ensures the legacy XML fixtures remain readable by the new path,
 * so the legacy XMLHelper code can eventually be removed.</p>
 *
 * <p>Test groups (all element types per .ggx file):
 * <ul>
 *   <li>GraGra (top-level structure, name, options)</li>
 *   <li>Types (NodeType, EdgeType, TypeGraph, AttrType declarations)</li>
 *   <li>Graphs (host graphs with Node/Edge children)</li>
 *   <li>Rules (LHS/RHS/Morphism/NAC/PAC/NestedAC)</li>
 *   <li>Matches</li>
 *   <li>Constraints (Formula, AtomConstraint)</li>
 *   <li>RuleSequences</li>
 * </ul>
 */
public class LegacyDomRegressionTest {

    private static final String OUTPUT_DIR = "target/legacy-dom-regression/";

    private File outputDir;

    @BeforeClass
    public void setUp() {
        TestDataHelper.requireAllLegacy();
        outputDir = new File(OUTPUT_DIR);
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }
        XMLSerialization.setUseNewXml(false);
    }

    @AfterClass
    public void tearDown() {
        XMLSerialization.setUseNewXml(false);
    }

    @DataProvider(name = "legacyGgxFiles")
    public Object[][] legacyGgxFiles() {
        Object[][] data = new String[TestDataHelper.LEGACY_GGX_FILES.length][1];
        for (int i = 0; i < TestDataHelper.LEGACY_GGX_FILES.length; i++) {
            data[i][0] = TestDataHelper.LEGACY_GGX_FILES[i];
        }
        return data;
    }

    // ---- DOM load + save + reload: structure preservation ----

    /**
     * Loads a legacy .ggx file with the DOM path, saves to output, reloads
     * the saved file, and verifies structural equivalence.
     *
     * <p>This is the primary regression test: it proves the new DOM path
     * can read legacy XML and produce a stable roundtrip.</p>
     */
    @Test(dataProvider = "legacyGgxFiles")
    public void testLegacyGgxDomRoundtrip(String legacyFilename) throws Exception {
        File legacyFile = TestDataHelper.resolveLegacy(legacyFilename);
        TestDataHelper.requireFile(legacyFile);

        String baseName = legacyFilename.replace(".ggx", "");

        // Step 1: Load legacy XML with DOM path
        GraGra graGra1 = new GraGra();
        XMLSerialization.loadWithDom(graGra1, legacyFile.getAbsolutePath());
        assertNotNull(graGra1.getName(),
            "DOM load should produce a named GraGra: " + legacyFilename);

        // Step 2: Save with DOM path
        File outputFile = new File(outputDir, baseName + "_dom.ggx");
        assertTrue(XMLSerialization.saveWithDom(graGra1, outputFile.getAbsolutePath()),
            "DOM save should succeed: " + legacyFilename);
        assertTrue(outputFile.exists() && outputFile.length() > 0,
            "Output file should be non-empty: " + legacyFilename);

        // Step 3: Reload the saved file with DOM path
        GraGra graGra2 = new GraGra();
        XMLSerialization.loadWithDom(graGra2, outputFile.getAbsolutePath());

        // Step 4: Verify structural equivalence
        assertEquals(graGra2.getName(), graGra1.getName(),
            "GraGra name should match after DOM roundtrip: " + legacyFilename);
        assertEquals(graGra2.getGraphsVec().size(), graGra1.getGraphsVec().size(),
            "Graph count should match: " + legacyFilename);
        assertEquals(graGra2.getRulesVec().size(), graGra1.getRulesVec().size(),
            "Rule count should match: " + legacyFilename);

        int typeCount1 = graGra1.getTypeSet() != null
            ? graGra1.getTypeSet().getTypesCount() : 0;
        int typeCount2 = graGra2.getTypeSet() != null
            ? graGra2.getTypeSet().getTypesCount() : 0;
        assertEquals(typeCount2, typeCount1,
            "Type count should match: " + legacyFilename);

        // Verify graph contents (nodes, edges)
        for (int i = 0; i < graGra1.getGraphsVec().size(); i++) {
            Graph g1 = graGra1.getGraphsVec().get(i);
            Graph g2 = graGra2.getGraphsVec().get(i);
            assertEquals(g2.getNodesCount(), g1.getNodesCount(),
                "Node count in graph " + i + " should match: " + legacyFilename);
            assertEquals(g2.getArcsCount(), g1.getArcsCount(),
                "Arc count in graph " + i + " should match: " + legacyFilename);
        }

        // Verify rule contents (LHS/RHS nodes, edges)
        for (int i = 0; i < graGra1.getRulesVec().size(); i++) {
            Rule r1 = graGra1.getRulesVec().get(i);
            Rule r2 = graGra2.getRulesVec().get(i);
            assertEquals(r2.getName(), r1.getName(),
                "Rule " + i + " name should match: " + legacyFilename);
            assertEquals(r2.getSource().getNodesCount(),
                r1.getSource().getNodesCount(),
                "Rule " + i + " LHS node count should match: " + legacyFilename);
            assertEquals(r2.getSource().getArcsCount(),
                r1.getSource().getArcsCount(),
                "Rule " + i + " LHS arc count should match: " + legacyFilename);
            assertEquals(r2.getTarget().getNodesCount(),
                r1.getTarget().getNodesCount(),
                "Rule " + i + " RHS node count should match: " + legacyFilename);
            assertEquals(r2.getTarget().getArcsCount(),
                r1.getTarget().getArcsCount(),
                "Rule " + i + " RHS arc count should match: " + legacyFilename);
        }
    }

    // ---- DOM path stability: save → reload → save → compare XML ----

    /**
     * Verifies that the DOM path is stable: saving twice produces identical
     * canonical XML for each legacy fixture.
     */
    @Test(dataProvider = "legacyGgxFiles")
    public void testDomPathStability(String legacyFilename) throws Exception {
        File legacyFile = TestDataHelper.resolveLegacy(legacyFilename);
        TestDataHelper.requireFile(legacyFile);

        String baseName = legacyFilename.replace(".ggx", "");

        // Load legacy XML with DOM path
        GraGra graGra = new GraGra();
        XMLSerialization.loadWithDom(graGra, legacyFile.getAbsolutePath());

        // Save (first time)
        File output1 = new File(outputDir, baseName + "_stable_1.ggx");
        XMLSerialization.saveWithDom(graGra, output1.getAbsolutePath());

        // Reload and save again
        GraGra graGraReloaded = new GraGra();
        XMLSerialization.loadWithDom(graGraReloaded, output1.getAbsolutePath());
        File output2 = new File(outputDir, baseName + "_stable_2.ggx");
        XMLSerialization.saveWithDom(graGraReloaded, output2.getAbsolutePath());

        // Canonical comparison; the native RuleScheme path no longer
        // carries the legacy reader's model side effects
        XmlCanonicalComparator.ComparisonResult result =
            XmlCanonicalComparator.compareFiles(output1, output2);
        assertTrue(result.isEqual(),
            "DOM path should be stable for " + legacyFilename + ": "
                + result.getMessage());
    }

    // ---- Grouped element verification per legacy file ----

    /**
     * Verifies that all element types present in the legacy file are
     * preserved through the DOM roundtrip.
     */
    @Test(dataProvider = "legacyGgxFiles")
    public void testAllElementTypesPreserved(String legacyFilename) throws Exception {
        File legacyFile = TestDataHelper.resolveLegacy(legacyFilename);
        TestDataHelper.requireFile(legacyFile);

        // Load with DOM path
        GraGra graGra = new GraGra();
        XMLSerialization.loadWithDom(graGra, legacyFile.getAbsolutePath());

        // Verify GraGra
        assertNotNull(graGra.getName(),
            "GraGra name should not be null: " + legacyFilename);

        // Verify Types
        if (graGra.getTypeSet() != null) {
            assertTrue(graGra.getTypeSet().getTypesCount() > 0,
                "Should have at least one type: " + legacyFilename);
        }

        // Verify Graphs
        assertTrue(graGra.getGraphsVec().size() > 0,
            "Should have at least one graph: " + legacyFilename);
        for (Graph g : graGra.getGraphsVec()) {
            assertNotNull(g.getName(), "Graph name should not be null: " + legacyFilename);
        }

        // Verify Rules
        for (Rule r : graGra.getRulesVec()) {
            assertNotNull(r.getName(), "Rule name should not be null: " + legacyFilename);
            assertNotNull(r.getSource(), "Rule LHS should not be null: " + legacyFilename);
            assertNotNull(r.getTarget(), "Rule RHS should not be null: " + legacyFilename);
        }

        // Verify Constraints
        int formulaCount = graGra.getConstraintsVec() != null
            ? graGra.getConstraintsVec().size() : 0;
        int atomicCount = 0;
        java.util.Enumeration<agg.cons.AtomConstraint> atomics = graGra.getAtomics();
        while (atomics.hasMoreElements()) {
            atomics.nextElement();
            atomicCount++;
        }
        // Constraint count should be consistent (not negative)
        assertTrue(formulaCount >= 0, "Formula count should be non-negative: " + legacyFilename);
        assertTrue(atomicCount >= 0, "Atomic count should be non-negative: " + legacyFilename);
    }

    // ---- .rsx and .cpx legacy files (legacy roundtrip) ----

    /**
     * Verifies that the .rsx legacy fixture can be loaded and re-saved
     * via the legacy XMLHelper path (structure preservation, not canonical
     * XML comparison, due to legacy roundtrip instabilities).
     */
    @Test
    public void testLegacyApplRuleSequenceRoundtrip() throws Exception {
        File legacyFile = TestDataHelper.resolveLegacy("appl_rule_sequence.rsx");
        TestDataHelper.requireFile(legacyFile);

        // Step 1: load the frozen reference with the DOM path
        agg.parser.CriticalPairOption option = new agg.parser.CriticalPairOption();
        agg.ruleappl.ApplRuleSequence ars = new agg.ruleappl.ApplRuleSequence(option);
        XMLSerialization.loadWithDom(ars, legacyFile.getAbsolutePath());
        assertNotNull(ars.getGraGra(),
            "DOM .rsx load should populate the embedded grammar");
        assertEquals("RuleSequenceTest", ars.getGraGra().getName(),
            "DOM .rsx load should restore the grammar name");
        assertFalse(ars.getRuleSequences().isEmpty(),
            "DOM .rsx load should bind the grammar's rule sequences");

        // Step 2: save with the DOM path
        File outputFile = new File(outputDir, "appl_rule_sequence_dom.rsx");
        assertTrue(XMLSerialization.saveWithDom(ars, outputFile.getAbsolutePath()),
            "DOM .rsx save should succeed");
        assertTrue(outputFile.exists() && outputFile.length() > 0,
            "Output .rsx should be non-empty");

        // Step 3: canonical comparison against the frozen legacy re-save of
        // the same load state (the legacy load binds the grammar's rule
        // sequences into the container, so the fresh reference has an empty
        // RuleSequences section)
        File resavedFile = new File("target/legacy_prep/appl_rule_sequence_resaved.rsx");
        assertTrue(resavedFile.exists() && resavedFile.length() > 0,
            "Re-saved .rsx reference is missing (run the legacy preparation "
                + "suite first: mvn test at the parent)");
        XmlCanonicalComparator.ComparisonResult result =
            XmlCanonicalComparator.compareFiles(resavedFile, outputFile);
        assertTrue(result.isEqual(),
            "Cross-system XML mismatch for appl_rule_sequence.rsx: "
                + result.getMessage());

        // Step 4: DOM stability: reload and save again
        agg.ruleappl.ApplRuleSequence reloaded =
            new agg.ruleappl.ApplRuleSequence(new agg.parser.CriticalPairOption());
        XMLSerialization.loadWithDom(reloaded, outputFile.getAbsolutePath());
        File stableFile = new File(outputDir, "appl_rule_sequence_stable.rsx");
        assertTrue(XMLSerialization.saveWithDom(reloaded, stableFile.getAbsolutePath()),
            "DOM .rsx stability save should succeed");
        XmlCanonicalComparator.ComparisonResult stableResult =
            XmlCanonicalComparator.compareFiles(outputFile, stableFile);
        assertTrue(stableResult.isEqual(),
            "DOM path should be stable for .rsx: " + stableResult.getMessage());
    }

    /**
     * Verifies that the .cpx legacy fixture can be loaded and re-saved
     * via the legacy XMLHelper path (structure preservation).
     */
    @Test
    public void testLegacyConflictsDependenciesRoundtrip() throws Exception {
        File legacyFile = TestDataHelper.resolveLegacy("conflicts_deps.cpx");
        TestDataHelper.requireFile(legacyFile);

        // Step 1: load the frozen reference with the DOM path
        agg.parser.ConflictsDependenciesContainer cdc =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(cdc, legacyFile.getAbsolutePath());
        assertNotNull(cdc.getGrammar(),
            "DOM .cpx load should populate the embedded grammar");
        assertEquals("BasicGraphTest", cdc.getGrammar().getName(),
            "DOM .cpx load should restore the grammar name");
        assertTrue(cdc.getContainerCount() > 0,
            "DOM .cpx load should create the pair containers");
        assertFalse(cdc.getLoadedCPAOptions().isEmpty(),
            "DOM .cpx load should restore the CPA options");

        // Step 2: save with the DOM path
        File outputFile = new File(outputDir, "conflicts_deps_dom.cpx");
        assertTrue(XMLSerialization.saveWithDom(cdc, outputFile.getAbsolutePath()),
            "DOM .cpx save should succeed");
        assertTrue(outputFile.exists() && outputFile.length() > 0,
            "Output .cpx should be non-empty");

        // Step 3: canonical comparison against the frozen reference
        XmlCanonicalComparator.ComparisonResult result =
            XmlCanonicalComparator.compareFiles(legacyFile, outputFile);
        assertTrue(result.isEqual(),
            "Cross-system XML mismatch for conflicts_deps.cpx: "
                + result.getMessage());

        // Step 4: DOM stability: reload and save again
        agg.parser.ConflictsDependenciesContainer reloaded =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(reloaded, outputFile.getAbsolutePath());
        File stableFile = new File(outputDir, "conflicts_deps_stable.cpx");
        assertTrue(XMLSerialization.saveWithDom(reloaded, stableFile.getAbsolutePath()),
            "DOM .cpx stability save should succeed");
        XmlCanonicalComparator.ComparisonResult stableResult =
            XmlCanonicalComparator.compareFiles(outputFile, stableFile);
        assertTrue(stableResult.isEqual(),
            "DOM path should be stable for .cpx: " + stableResult.getMessage());
    }


    // ---- .cpx computed critical pairs (generated prep fixtures) ----

    /**
     * Resolves a generated .cpx reference produced by the legacy
     * preparation suite.
     */
    private File prepCpxFile(String filename) {
        File refFile = new File("target/legacy_prep/", filename);
        assertTrue(refFile.exists() && refFile.length() > 0,
            "Generated .cpx reference is missing (run the legacy preparation"
                + " suite first: mvn -pl test/test_agg/legacy_agg -am test"
                + " -Dtest=LegacyPreparationTest): " + refFile.getPath());
        return refFile;
    }

    /** Counts the overlapping pairs stored in the exclude container. */
    private int countOverlappingPairs(agg.parser.ExcludePairContainer pc) {
        int count = 0;
        for (Object o1 : pc.getExcludeContainer().values()) {
            for (Object o2 : ((Map<?, ?>) o1).values()) {
                agg.util.Pair<?, ?> p = (agg.util.Pair<?, ?>) o2;
                if (Boolean.TRUE.equals(p.first) && p.second != null) {
                    count += ((List<?>) p.second).size();
                }
            }
        }
        return count;
    }

    /**
     * Verifies that the generated .cpx fixture with computed conflict and
     * dependency entries (plain overlaps) survives the DOM roundtrip. The
     * DOM save is compared canonically against the RAW reference, not the
     * legacy re-save: the legacy reader mutates the grammar on load
     * (LHS/RHS renames, type name representations) and the DOM path does
     * not replicate those mutations.
     */
    @Test
    public void testLegacyConflictsDependenciesComputedPlainRoundtrip() throws Exception {
        File refFile = prepCpxFile("gen_conflicts_computed.cpx");

        // Step 1: load the raw reference with the DOM path
        agg.parser.ConflictsDependenciesContainer cdc =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(cdc, refFile.getAbsolutePath());
        assertNotNull(cdc.getGrammar(),
            "DOM .cpx load should populate the embedded grammar");
        assertNotNull(cdc.getExcludePairContainer(),
            "DOM .cpx load should create the conflict container");
        assertEquals(countOverlappingPairs(cdc.getExcludePairContainer()), 2,
            "DOM .cpx load should restore the 2 computed conflict overlaps");
        assertNotNull(cdc.getDependencyPairContainer(),
            "DOM .cpx load should create the dependency container");
        assertEquals(countOverlappingPairs(cdc.getDependencyPairContainer()), 2,
            "DOM .cpx load should restore the 2 computed dependency overlaps");

        // Step 2: save with the DOM path
        File outputFile = new File(outputDir, "conflicts_computed_dom.cpx");
        assertTrue(XMLSerialization.saveWithDom(cdc, outputFile.getAbsolutePath()),
            "DOM .cpx save should succeed");

        // Step 3: canonical comparison against the RAW reference
        XmlCanonicalComparator.ComparisonResult result =
            XmlCanonicalComparator.compareFiles(refFile, outputFile);
        assertTrue(result.isEqual(),
            "Cross-system XML mismatch for gen_conflicts_computed.cpx: "
                + result.getMessage());

        // Step 4: DOM stability: reload and save again
        agg.parser.ConflictsDependenciesContainer reloaded =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(reloaded, outputFile.getAbsolutePath());
        File stableFile = new File(outputDir, "conflicts_computed_stable.cpx");
        assertTrue(XMLSerialization.saveWithDom(reloaded, stableFile.getAbsolutePath()),
            "DOM .cpx stability save should succeed");
        XmlCanonicalComparator.ComparisonResult stableResult =
            XmlCanonicalComparator.compareFiles(outputFile, stableFile);
        assertTrue(stableResult.isEqual(),
            "DOM path should be stable for computed .cpx: "
                + stableResult.getMessage());
    }

    /**
     * Verifies the DOM roundtrip for computed conflict entries with a NAC
     * overlap (second morphism reconstructed through
     * extendLeftGraphByNAC), compared canonically against the RAW
     * reference.
     */
    @Test
    public void testLegacyConflictsDependenciesComputedNacRoundtrip() throws Exception {
        File refFile = prepCpxFile("gen_conflicts_computed_nac.cpx");

        agg.parser.ConflictsDependenciesContainer cdc =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(cdc, refFile.getAbsolutePath());
        assertNotNull(cdc.getExcludePairContainer(),
            "DOM .cpx load should create the conflict container");
        assertEquals(countOverlappingPairs(cdc.getExcludePairContainer()), 1,
            "DOM .cpx load should restore the NAC conflict overlap");
        // the NAC overlap carries the (morphL2iso, morphNACiso) pair
        Map<?, ?> secondPart = cdc.getExcludePairContainer()
            .getExcludeContainer().values().iterator().next();
        agg.util.Pair<?, ?> p =
            (agg.util.Pair<?, ?>) secondPart.values().iterator().next();
        List<?> overlaps = (List<?>) p.second;
        agg.util.Pair<?, ?> p2i = (agg.util.Pair<?, ?>) overlaps.get(0);
        assertNotNull(p2i.second,
            "the NAC overlap should restore the iso morphism pair");

        File outputFile = new File(outputDir, "conflicts_computed_nac_dom.cpx");
        assertTrue(XMLSerialization.saveWithDom(cdc, outputFile.getAbsolutePath()),
            "DOM .cpx save should succeed");

        XmlCanonicalComparator.ComparisonResult result =
            XmlCanonicalComparator.compareFiles(refFile, outputFile);
        assertTrue(result.isEqual(),
            "Cross-system XML mismatch for gen_conflicts_computed_nac.cpx: "
                + result.getMessage());

        agg.parser.ConflictsDependenciesContainer reloaded =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(reloaded, outputFile.getAbsolutePath());
        File stableFile = new File(outputDir, "conflicts_computed_nac_stable.cpx");
        assertTrue(XMLSerialization.saveWithDom(reloaded, stableFile.getAbsolutePath()),
            "DOM .cpx stability save should succeed");
        XmlCanonicalComparator.ComparisonResult stableResult =
            XmlCanonicalComparator.compareFiles(outputFile, stableFile);
        assertTrue(stableResult.isEqual(),
            "DOM path should be stable for the NAC computed .cpx: "
                + stableResult.getMessage());
    }

    /**
     * Verifies the DOM roundtrip for computed conflict entries with a PAC
     * overlap. The PAC overlap is lossy in the reader (the pacname mapping
     * of a pure PAC arc is not reconstructed, the orig2copy map of the
     * legacy reader only knows LHS nodes), so this test checks stability
     * and structure instead of a canonical comparison against the RAW
     * reference.
     */
    @Test
    public void testLegacyConflictsDependenciesComputedPacRoundtrip() throws Exception {
        File refFile = prepCpxFile("gen_conflicts_computed_pac.cpx");

        agg.parser.ConflictsDependenciesContainer cdc =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(cdc, refFile.getAbsolutePath());
        assertNotNull(cdc.getExcludePairContainer(),
            "DOM .cpx load should create the conflict container");
        assertEquals(countOverlappingPairs(cdc.getExcludePairContainer()), 1,
            "DOM .cpx load should restore the PAC conflict overlap");

        Map<?, ?> secondPart = cdc.getExcludePairContainer()
            .getExcludeContainer().values().iterator().next();
        agg.util.Pair<?, ?> p =
            (agg.util.Pair<?, ?>) secondPart.values().iterator().next();
        List<?> overlaps = (List<?>) p.second;
        assertEquals(overlaps.size(), 1,
            "one PAC overlap should be restored");
        agg.util.Pair<?, ?> p2i = (agg.util.Pair<?, ?>) overlaps.get(0);
        assertNotNull(p2i.second,
            "the PAC overlap should restore the (embedPac, morphL2PACiso) pair");
        agg.util.Pair<?, ?> p1 = (agg.util.Pair<?, ?>) p2i.first;
        agg.xt_basis.OrdinaryMorphism second =
            (agg.xt_basis.OrdinaryMorphism) p1.second;
        assertEquals(second.getSize(), 2,
            "the lossy PAC read should keep the 2 LHS mappings of the"
                + " second morphism");

        // Save, reload, save: the DOM output must be stable
        File outputFile = new File(outputDir, "conflicts_computed_pac_dom.cpx");
        assertTrue(XMLSerialization.saveWithDom(cdc, outputFile.getAbsolutePath()),
            "DOM .cpx save should succeed");
        agg.parser.ConflictsDependenciesContainer reloaded =
            new agg.parser.ConflictsDependenciesContainer();
        XMLSerialization.loadWithDom(reloaded, outputFile.getAbsolutePath());
        File stableFile = new File(outputDir, "conflicts_computed_pac_stable.cpx");
        assertTrue(XMLSerialization.saveWithDom(reloaded, stableFile.getAbsolutePath()),
            "DOM .cpx stability save should succeed");
        XmlCanonicalComparator.ComparisonResult stableResult =
            XmlCanonicalComparator.compareFiles(outputFile, stableFile);
        assertTrue(stableResult.isEqual(),
            "DOM path should be stable for the PAC computed .cpx: "
                + stableResult.getMessage());
    }
}
